apiVersion: v1
kind: ServiceAccount
metadata:
  name: zabbix-service-account
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zabbix-cluster-role
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/stats
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zabbix-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zabbix-cluster-role
subjects:
- kind: ServiceAccount
  name: zabbix-service-account
  namespace: monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: zabbix-token
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: zabbix-service-account
type: kubernetes.io/service-account-token
